on:
  push:
    branches: main

name: Render Quarto site

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        uses: quarto-dev/quarto-actions/render@v2
        
      - name: Commit rendered site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add site/
          git commit -m "Re-build site" || echo "No changes to commit"
          git push origin || echo "No changes to commit"